# FROM node:18-alpine

# WORKDIR /app

# COPY package*.json ./

# RUN npm ci --only=production

# COPY . .

# EXPOSE 5555

# CMD ["npm", "start"]

FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5555

CMD ["npm", "start"]