name: Frontend-CI

on:
  push:
    branches:
      - cicd
    paths:
      - frontend/**

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      
      - name: Snyk Scan
        uses: snyk/actions/node@master
        with:
          command: test
          args: --file=frontend/package.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Build Image
        run: docker build -t book-store-frontend:${{ github.sha }} ./frontend

      - name: Check Docker Image
        run: docker images

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: book-store-frontend:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Sucess Message
        run: echo "Sucessfully Done"